# -*- coding: utf-8 -*-
"""linear_regression.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1whtJZ71yE08OvbuR1suaYxEOUenu-THi
"""

from sklearn.linear_model import LinearRegression

# Data
X = [[1], [2], [3], [4], [5]]  # Hours studied
y = [40, 50, 60, 70, 80]       # Marks obtained

# Model
model = LinearRegression()
model.fit(X, y)

# Predict marks for 6 hours of study
predicted_marks = model.predict([[6]])
print("Predicted marks for 6 hours of study:", predicted_marks[0])